routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('sync-db', 'HomeController@syncDb');

Route::group(['middleware' => 'auth'], function () {

    // Datatabes Routes
    Route::group(['namespace' => 'Book'], function () {
        Route::get('datatable/books', 'BookController@datatable')->name('book-datatable');
    });

    // Book Model Routes
    Route::group(['namespace' => 'Book'], function () {
        Route::resource('book', 'BookController')->names([
            'index' => 'book-index',
            'create' => 'book-create',
            'store' => 'book-store',
            'edit' => 'book-edit',
            'update' => 'book-update',
            'destroy' => 'book-destroy'
        ]);

        Route::post('book/create-chapter', 'BookController@createChapter')->name('book-create-chapter');
        Route::get('book/view-chapter/{id}', 'BookController@viewChapter')->name('book-view-chapter');
        Route::get('book/chapter/{id}/create-page', 'BookController@createPage')->name('book-create-page');
        Route::post('book/chapter/{id}/create-page', 'BookController@storePage')->name('book-store-page');
        Route::get('book/{bid}/chapter/{cid}/page/{pid}', 'BookController@viewPage')->name('book-view-page');
        Route::put('book/{bid}/chapter/{cid}/page/{pid}', 'BookController@updatePage')->name('book-update-page');

    });
    // BookCategory Model Routes
    Route::group(['namespace' => 'Category'], function () {
        Route::resource('category', 'CategoryController')->names([
            'index' => 'category-index',
            'create' => 'category-create',
            'store' => 'category-store',
            'edit' => 'category-edit',
            'update' => 'category-update',
            'destroy' => 'category-destroy'
        ]);
    });

    // BookCategory Model Routes
    Route::group(['namespace' => 'Author'], function () {
        Route::resource('author', 'AuthorController')->names([
            'index' => 'author-index',
            'create' => 'author-create',
            'store' => 'author-store',
            'edit' => 'author-edit',
            'update' => 'author-update',
            'destroy' => 'author-destroy'
        ]);
    });

    // BookCategory Model Routes
    Route::group(['namespace' => 'Publisher'], function () {
        Route::resource('publisher', 'PublisherController')->names([
            'index' => 'publisher-index',
            'create' => 'publisher-create',
            'store' => 'publisher-store',
            'edit' => 'publisher-edit',
            'update' => 'publisher-update',
            'destroy' => 'publisher-destroy'
        ]);
    });

    Route::group(['namespace' => 'Section'], function(){
       Route::resource('section', 'SectionController')->names([
          'index' => 'section-index',
           'store' => 'section-store',
           'update' => 'section-update',
           'show' => 'section-show'
       ]);
       Route::post('add-books-to-section/{id}','SectionController@addBooks')->name('section-add-books');
    });

    Route::group(['namespace' => 'Banner'],function(){
        Route::resource('banner', 'BannerController')->names([
            'index' => 'banner-index',
            'store' => 'banner-store',
            'update' => 'banner-update',
            'show' => 'banner-show'
        ]);
    });

    Route::group(['namespace' => 'Library'], function(){
       Route::resource('library', 'LibraryController')->names([
           'index' => 'library-index',
           'store' => 'library-store',
           'update' => 'library-update',
           'show' => 'library-show'
       ]);
    });

    Route::group(['namespace' => 'Article'], function(){
        Route::resource('article', 'ArticleController')->names([
            'index' => 'article-index',
            'store' => 'article-store',
            'update' => 'article-update',
            'show' => 'article-show',
            'create' => 'article-create',
            'edit' => 'article-edit'
        ]);
    });

    //Article category
    Route::group(['namespace' => 'ArticleCategory'], function () {
        Route::resource('article-category', 'ArticleCategoryController')->names([
            'index' => 'article-category-index',
            'create' => 'article-category-create',
            'store' => 'article-category-store',
            'edit' => 'article-category-edit',
            'update' => 'article-category-update',
            'destroy' => 'article-category-destroy'
        ]);
    });

    // Misc images
    Route::group(['namespace' => 'MiscImage'], function(){
       Route::resource('misc-images', 'MiscImageController');
    });

});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];
    protected $casts = ['version' => 'integer'];
    protected $fillable = [
        'title',
        'summary',
        'image',
        'version',
        'status',
        'published_at',
        'language',
        'category_id',
        'author_id',
        'publisher_id',
        'library_id'
    ];

    public function category()
    {
        return $this->belongsTo(BookCategory::class, 'category_id');
    }

    public function author()
    {
        return $this->belongsTo(BookAuthor::class, 'author_id');
    }

    public function publisher()
    {
        return $this->belongsTo(BookPublisher::class, 'publisher_id');
    }

    public function getImageAttribute($value)
    {
        if($value)
            return url('/') . '/' . $value;
        return null;
    }

    public function chapters()
    {
        return $this->hasMany(BookChapter::class);
    }

    public function pages()
    {
        return $this->hasMany(BookChapterPage::class);
    }

    public function library()
    {
        return $this->belongsTo(Library::class);
    }

}

app/Http/Controllers/Book/BookController.php
<?php

namespace App\Http\Controllers\Book;

use App\Http\Controllers\Breadcrumb;
use App\Http\Controllers\Controller;
use App\Http\Repositories\BookAuthorRepository;
use App\Http\Repositories\BookCategoryRepository;
use App\Http\Repositories\BookPublisherRepository;
use App\Http\Repositories\BookRepository;
use App\Http\Repositories\LibraryRepository;
use Illuminate\Http\Request;
use Validator;

class BookController extends Controller
{
    protected $book;
    protected $request;
    protected $bookAuthor;
    protected $bookCategory;
    protected $bookPublisher;

    public function __construct(
        Request $request,
        BookRepository $book,
        BookCategoryRepository $bookCategory,
        BookAuthorRepository $bookAuthor,
        BookPublisherRepository $bookPublisher,
        LibraryRepository $libraryRepository
    )
    {
        $this->book = $book;
        $this->request = $request;
        $this->bookAuthor = $bookAuthor;
        $this->bookCategory = $bookCategory;
        $this->bookPublisher = $bookPublisher;
        $this->library = $libraryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumb = new Breadcrumb();
        $breadcrumb = $breadcrumb->generate();
        return view('book.index-dt', compact('breadcrumb'));
    }

    public function datatable()
    {
        return $books = $this->book->listDatatable();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumb = new Breadcrumb();
        $breadcrumb = $breadcrumb->generate();

        $categories = $this->bookCategory->list();
        $authors = $this->bookAuthor->list();
        $publishers = $this->bookPublisher->list();
        $libraries = $this->library->list();
        return view('book.create', compact('categories', 'authors', 'publishers', 'breadcrumb', 'libraries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {

        $request = $this->request;
        $data = $request->all();

        $v = Validator::make($data, [
            'title' => 'required',
            'version' => 'required|numeric',
            'image' => 'image'
        ]);

        if ($v->fails()) return redirect()->back()->withErrors($v);

        $response = $this->book->store($data);
        if ($response) {
            return redirect(route('book-index'))->with('success', MESSAGE_GENERAL_CREATE_SUCCESS);
        } else {
            return redirect()->back()->with('error', MESSAGE_GENERAL_CREATE_ERROR);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $breadcrumb = new Breadcrumb();
        $breadcrumb = $breadcrumb->generate();

        $book = $this->book->getOnebook($id);
        $categories = $this->bookCategory->list();
        $authors = $this->bookAuthor->list();
        $publishers = $this->bookPublisher->list();
        $libraries = $this->library->list();
        return view('book.edit', compact('book', 'categories', 'authors', 'publishers', 'breadcrumb', 'libraries'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        $request = $this->request;
        $data = $request->all();

        $v = Validator::make($data, [
            'title' => 'required',
            'version' => 'required|numeric',
            'image' => 'image'
        ]);

        if ($v->fails()) return redirect()->back()->withErrors($v);

        $response = $this->book->update($id, $data);
        if ($response) {
            return back()->with('success', MESSAGE_GENERAL_UPDATE_SUCCESS);
        } else {
            return redirect()->back()->with('error', MESSAGE_GENERAL_UPDATE_ERROR);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function createChapter()
    {
        $request = $this->request;
        $response = $this->book->createChapter($request->all());
        if ($response) {
            if ($request->ajax())
                return response()->json([
                    'status' => STATUS_SUCCESS,
                    'message' => MESSAGE_GENERAL_CREATE_SUCCESS,
                    'data' => [
                        'chapter' => $response
                    ]
                ]);
            else
                return back()->with('success', MESSAGE_GENERAL_CREATE_SUCCESS);
        } else {
            if ($request->ajax())
                return response()->json([
                    'status' => STATUS_FAIL,
                    'message' => MESSAGE_GENERAL_CREATE_ERROR,
                    'data' => [

                    ]
                ]);
            else
                return redirect()->back()->with('error', MESSAGE_GENERAL_CREATE_ERROR);
        }
    }

    public function viewChapter($id)
    {
        $chapter = $this->book->viewChapter($id);

        $breadcrumb = new Breadcrumb();
        $breadcrumb = $breadcrumb->generate([$chapter->book_id]);

        return view('book.view-chapter', compact('chapter', 'breadcrumb'));
    }

    public function createPage($id)
    {

        $chapter = $this->book->viewChapter($id);

        $breadcrumb = new Breadcrumb();
        $breadcrumb = $breadcrumb->generate([$chapter->book_id, $chapter->id]);

        return view('book.create-page', compact('chapter', 'breadcrumb'));
    }

    public function storePage($id)
    {
        $request = $this->request;
        $response = $this->book->storePage($request->all());
        if ($response)
            return redirect()->back()->with('success', MESSAGE_GENERAL_CREATE_SUCCESS);

        return redirect()->back()->with('error', MESSAGE_GENERAL_CREATE_ERROR);
    }

    public function viewPage($bid, $cid, $pid)
    {
        $page = $this->book->viewPage($pid);

        $breadcrumb = new Breadcrumb();
        $breadcrumb = $breadcrumb->generate([$page->book_id, $page->book_chapter_id]);

        return view('book.view-page', compact('page', 'breadcrumb'));
    }

    public function updatePage($bid, $cid, $pid)
    {

        $this->book->updatePage($pid, $this->request->all());
        return redirect()->back()->with('success', MESSAGE_GENERAL_UPDATE_SUCCESS);
    }
}

resources/views/book/create-page.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="{{route('book-store-page', $chapter->id)}}">
        @csrf
        <div class="row">
            <div class="col-md-12">

                <p>
                    <label for="sort_order">الترتيب</label>
                    <input type="number" class="form-control" name="sort_order" id="sort_order">
                </p>

                <p>
                    <label for="content">محتوى الصفحة كما يجب ان يظهر</label>
                    <textarea class="form-control" id="content" name="content"></textarea>
                </p>

                <input type="hidden" name="book_id" value="{{$chapter->book_id}}">
                <input type="hidden" name="book_chapter_id" value="{{$chapter->id}}">

            </div>
            <div class="col-md-4 offset-8">
                <input type="submit" value="حفظ" class="form-control btn btn-primary">
            </div>
        </div>
    </form>

    <hr>

    <form method="POST" action="{{route('misc-images.store')}}" enctype="multipart/form-data" id="upload-image">
        @csrf
        <div class="row">
            <div class="col-md-8">
                <input type="file" name="image" id="image">
            </div>
            <div class="col-md-4">
                <button class="btn btn-success form-control">تحميل الصورة</button>
            </div>
        </div>
    </form>

    <div id="results"></div>

    <br>
    <br>

@endsection

@section('script')

    <script>
        CKEDITOR.replace('content', {
            language: 'ar',
            height: 500
        });

        $('#upload-image').submit(function (e) {
            e.preventDefault();
            $.ajax({
                url: '{{route('misc-images.store')}}',
                type: 'POST',
                data: new FormData(this),
                cache: false,
                datatype: 'JSON',
                processData: false,
                contentType: false,
                success: function (data) {
                    if (data.status == 1) {
                        $('#image').val('');
                        $('#results').append(data.data+'<br>');
                    }
                }, error: function () {

                }
            });
        });

    </script>

@endsection

resources/views/book/create.blade.php
@extends('layouts.app')

@section('content')
    <form method="POST" action="{{route('book-store')}}" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <p>
                    <label for="title">العنوان</label>
                    <input type="text" class="form-control" id="title" name="title">
                </p>
            </div>
            <div class="col-md-12">
                <p>
                    <label for="summary">وصف مصغر</label>
                    <textarea class="form-control" id="summary" name="summary"
                              style="height: 150px; resize: none"></textarea>
                </p>
            </div>
            <div class="col-md-6">
                <p>
                    <label for="image">الصورة</label>
                    <input type="file" class="form-control" id="image" name="image">
                </p>
            </div>
            <div class="col-md-6">
                <p>
                    <label for="status">الحالة</label>
                    <select class="form-control" id="status" name="status">
                        <option value="1">منشور</option>
                        <option value="0">غير منشور</option>
                    </select>
                </p>
            </div>
            <div class="col-md-3">
                <p>
                    <label for="version">رقم الاصدار</label>
                    <input type="number" class="form-control" id="version" name="version">
                </p>
            </div>
            <div class="col-md-3">
                <p>
                    <label for="published_at">تاريخ الاصدار</label>
                    <input type="date" class="form-control" id="published_at" name="published_at">
                </p>
            </div>
            <div class="col-md-3">
                <p>
                    <label for="language">اللغة</label>
                    <input type="text" class="form-control" id="language" name="language">
                </p>
            </div>
            <div class="col-md-3">
                <p>
                    <label for="library_id">المكتبة</label>
                    <select class="form-control" id="library_id" name="library_id">
                        @foreach($libraries as $library)
                            @if($library->id != 3)
                            <option value="{{$library->id}}">{{$library->name}}</option>
                            @endif
                        @endforeach
                    </select>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <label for="category">الفئة</label>
                    <select class="form-control" id="category" name="category_id">
                        @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                    </select>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <label for="author">الكاتب</label>
                    <select class="form-control" id="author" name="author_id">
                        @foreach($authors as $author)
                            <option value="{{$author->id}}">{{$author->name}}</option>
                        @endforeach
                    </select>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <label for="publisher">دار النشر</label>
                    <select class="form-control" id="publisher" name="publisher_id">
                        @foreach($publishers as $publisher)
                            <option value="{{$publisher->id}}">{{$publisher->name}}</option>
                        @endforeach
                    </select>
                </p>
            </div>
            <div class="col-md-8"></div>
            <div class="col-md-4">
                <p>
                    <input type="submit" class="form-control btn btn-primary" value="حفظ">
                </p>
            </div>
        </div>
    </form>
@endsection

resources/views/book/edit.blade.php
@extends('layouts.app')

@section('content')
    <form method="POST" action="{{route('book-update', $book->id)}}" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="row">
            <div class="col-md-12">
                <p>
                    <label for="title">العنوان</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{$book->title}}">
                </p>
            </div>
            <div class="col-md-12">
                <p>
                    <label for="summary">وصف مصغر</label>
                    <textarea class="form-control" id="summary" name="summary"
                              style="height: 150px; resize: none">{{$book->summary}}</textarea>
                </p>
            </div>
            <div class="col-md-2">
                @if($book->image)
                    <img src="{{asset($book->image)}}" style="width: 100%">
                @else
                    لا يوجد صورة
                @endif
            </div>
            <div class="col-md-4">
                <p>
                    <label for="image">الصورة</label>
                    <input type="file" class="form-control" id="image" name="image">
                </p>
            </div>
            <div class="col-md-6">
                <p>
                    <label for="status">الحالة</label>
                    <select class="form-control" id="status" name="status">
                        <option value="1" {{($book->status == 1) ? 'selected' : ''}}>منشور</option>
                        <option value="0" {{($book->status == 0) ? 'selected' : ''}}>غير منشور</option>
                    </select>
                </p>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-3">
                <p>
                    <label for="version">رقم الاصدار</label>
                    <input type="number" class="form-control" id="version" name="version" value="{{$book->version}}">
                </p>
            </div>
            <div class="col-md-3">
                <p>
                    <label for="published_at">تاريخ الاصدار</label>
                    <input type="date" class="form-control" id="published_at" name="published_at"
                           value="{{$book->published_at}}">
                </p>
            </div>
            <div class="col-md-3">
                <p>
                    <label for="language">اللغة</label>
                    <input type="text" class="form-control" id="language" name="language" value="{{$book->language}}">
                </p>
            </div>
            <div class="col-md-3">
                <p>
                    <label for="library_id">المكتبة</label>
                    <select class="form-control" id="library_id" name="library_id">
                        @foreach($libraries as $library)
                            @if($library->id != 3)
                                <option {{($library->id == $book->library_id) ? 'selected' : ''}} value="{{$library->id}}">{{$library->name}}</option>
                            @endif
                        @endforeach
                    </select>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <label for="category">الفئة</label>
                    <select class="form-control" id="category" name="category_id">
                        @foreach($categories as $category)
                            <option value="{{$category->id}}" {{($book->category_id == $category->id) ? 'selected' : ''}}>{{$category->name}}</option>
                        @endforeach
                    </select>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <label for="author">الكاتب</label>
                    <select class="form-control" id="author" name="author_id">
                        @foreach($authors as $author)
                            <option value="{{$author->id}}" {{($book->author_id == $author->id) ? 'selected' : ''}}>{{$author->name}}</option>
                        @endforeach
                    </select>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <label for="publisher">دار النشر</label>
                    <select class="form-control" id="publisher" name="publisher_id">
                        @foreach($publishers as $publisher)
                            <option value="{{$publisher->id}}" {{($book->publisher_id == $publisher->id) ? 'selected' : ''}}>{{$publisher->name}}</option>
                        @endforeach
                    </select>
                </p>
            </div>
            <div class="col-md-8"></div>
            <div class="col-md-4">
                <p>
                    <input type="submit" class="form-control btn btn-success" value="حفظ">
                </p>
            </div>
        </div>
    </form>

    <hr>

    <div class="row">
        <div class="col-md-10">
            <h3>أقسام الكتاب</h3>
        </div>
        <div class="col-m-2 text-left">
            <h3><a href="#" data-toggle="modal" data-target="#modal-create">قسم جديد</a></h3>
        </div>
    </div>

    <hr>

    <div class="row">
        @if(count($book->chapters) > 0)
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>الترتيب</th>
                        <th>الاسم</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($book->chapters as $chapter)
                        <tr>
                            <td>{{$chapter->sort_order}}</td>
                            <td>{{$chapter->name}}</td>
                            <td><a href="{{route('book-view-chapter',$chapter->id)}}">مشاهدة</a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        @else
            <div class="col-md-12">
                <div class="alert alert-warning">ان هذا الكتاب لا يحتوي على اي قسم</div>
            </div>
        @endif
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" id="modal-create">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">قسم جديد</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="#" enctype="multipart/form-data" id="form-create">
                        @csrf
                        <p>
                            <label for="name">الاسم</label>
                            <input type="text" class="form-control" placeholder="الاسم" name="name">
                        </p>
                        <p>
                            <label for="sort_order">الترتيب</label>
                            <input type="number" class="form-control" name="sort_order" placeholder="الترتيب">
                        </p>
                        <input type="hidden" name="book_id" value="{{$book->id}}">
                        <button type="submit" class="btn btn-primary">حفظ</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')

    <script>
        $('#form-create').submit(function (e) {
            e.preventDefault();

            $.ajax({
                url: '{{route('book-create-chapter')}}',
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                datatype: 'JSON',
                success: function (data) {
                    if (data.status == 1)
                        location.reload();
                }, error: function () {

                }
            });

        });
    </script>

@endsection

resources/views/book/view-page.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="{{route('book-update-page', [$page->book_id,$page->book_chapter_id,$page->id])}}">
        @csrf
        @method('put')
        <div class="row">
            <div class="col-md-12">

                <p>
                    <label for="sort_order">الترتيب</label>
                    <input type="number" class="form-control" name="sort_order" id="sort_order"
                           value="{{$page->sort_order}}">
                </p>

                <p>
                    <label for="content">محتوى الصفحة كما يجب ان يظهر</label>
                    <textarea class="form-control" id="content" name="content">{{$page->content}}</textarea>
                </p>

                <input type="hidden" name="book_id" value="{{$page->book_id}}">
                <input type="hidden" name="book_chapter_id" value="{{$page->book_chapter_id}}">

            </div>
            <div class="col-md-4 offset-8">
                <input type="submit" value="حفظ" class="form-control btn btn-primary">
            </div>
        </div>
    </form>

    <hr>

    <form method="POST" action="{{route('misc-images.store')}}" enctype="multipart/form-data" id="upload-image">
        @csrf
        <div class="row">
            <div class="col-md-8">
                <input type="file" name="image" id="image">
            </div>
            <div class="col-md-4">
                <button class="btn btn-success form-control">تحميل الصورة</button>
            </div>
        </div>
    </form>

    <div id="results"></div>

    <br>
    <br>


@endsection

@section('script')

    <script>
        CKEDITOR.replace('content', {
            language: 'ar',
            height: 500
        });

        $('#upload-image').submit(function (e) {
            e.preventDefault();
            $.ajax({
                url: '{{route('misc-images.store')}}',
                type: 'POST',
                data: new FormData(this),
                cache: false,
                datatype: 'JSON',
                processData: false,
                contentType: false,
                success: function (data) {
                    if (data.status == 1) {
                        $('#image').val('');
                        $('#results').append(data.data + '<br>');
                    }
                }, error: function () {

                }
            });
        });

    </script>

@endsection